@startuml
'https://plantuml.com/class-diagram

Title Class Diagram - Exposição

class Quadro{
- designacao : String
- nomeAutor : String
- anoCriacao : int
}

class Exposicao{
- designacao : String
- anoRealizacao : int
- quadros : Quadro
+ adicionarQuadro(quadro) : boolean
+ removerQuadro(quadro) : boolean
}

Exposicao --> "0...* " Quadro : has

@enduml